FROM node:20.10.0

WORKDIR /app

COPY package*.json ./

ARG MONGO_URI
ARG MONGO_DB
ARG RAZORPAY_KEY_ID
ARG RAZORPAY_KEY_SECRET

ENV PORT=5001
ENV MONGO_URI=${MONGO_URI}
ENV MONGO_DB=${MONGO_DB}
ENV RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
ENV RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}

RUN npm install && npm cache clean --force

COPY . .

EXPOSE 5001

CMD ["npm", "run", "dev"]
